accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
                   name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.Signup.as_view(), name='signup'),
]

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug:the_slug>', views.SingleGroup.as_view(), name='single')
]

socialplatform/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='Home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('groups/', include(('groups.urls', 'groups'), namespace='groups')),
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.

# Quick Note: models.py is to define the data model for database
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

groups/models.py
from django.db import models
from django.utils.text import slugify
import misaka
from django.contrib.auth import get_user_model
from django import template
from django.urls import reverse
# Create your models here.


User = get_user_model()
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='',blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('group:single', kwargs={'slug':self.slug})

    class Meta:
        ordering:['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

        unique_together = ('group', 'user')

posts/models.py
from django.db import models
from django.core.urls import reverse
from django.conf import settings

import misaka
from groups.models import Group

from django.contrib.auth import get_user_model

# Create your models here.


User = get_user_model()
class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts',null=True,blank=True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_irl(self):
        return reverse('posts:single', kwargs={'username':self.username,
                                               'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserSignUpForm(UserCreationForm):

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Note: (Custom Label)
        #      1. 'username' and 'email' is the field name in the database,
        #         which we get from get_user_model (built-in method)
        #      2. 'Display Name' and 'Email Address' are the name that will
        #         be shown on the website

        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = "Email Address"

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms
# Create your views here.

class Signup(CreateView):
    form_class = forms.UserSignUpForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

groups/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views import generic

from groups.models import Group, GroupMember

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    # We just want the user edit name and description in the Group model
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

posts/views.py
from django.shortcuts import render

# Create your views here.

socialplatform/views.py
from django.views.generic import TemplateView


class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'
    
class HomePage(TemplateView):
    template_name = 'index.html'

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
  <h1>Log In</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class='btn btn-default' value="Login">
  </form>

</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
  <h1>Sign Up</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class='btn btn-default' value="Sign up">
  </form>

</div>

{% endblock %}

groups/templates/group_list.html/group_form.html
{% extend "groups/group_base.html" %}

{% load bootstrap3 %}

{% block group_content %}
<h4> Create a new group! </h4>

  <form action="{% url 'groups:create' %}" method="POST" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class='btn btn-primary btn-large' value="Create">
  </form>

{% endblock %}

groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

<h1>{{ group.name }}</h1>
<h2>Member Count: {{ group.members.count }}</h2>

<div class="content">
  {% if user in group.members.all %}
    <a href="{% url 'group:leave' slug=group.slug %}
              class = btn btn-lg btn-fill btn-warning" >
            <span class = 'glyphicon glyphicon-remove-circle'></span>Leave</a>
  {% else %}
    <a href="{% url 'group:join' slug=group.slug %}
              class = btn btn-lg btn-fill btn-warning" >
              <span class = 'glyphicon glyphicon-ok-circle'></span>Join</a>
  {% endif %}

{% endblock %}

{% block group_content %}
<div class="col-md-8">
  {% if group.posts.count == 0%}
    <h2>No posts in this group yet</h2>
  {% else %}
    {% include "post/_post.html" %}
  {% endif %}

{% endblock %}


</div>

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}

{% load bootstrap3 %}

{% block group_content %}
<h4> Create a new group! </h4>

  <form action="{% url 'groups:create' %}" method="POST" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class='btn btn-primary btn-large' value="Create">
  </form>

{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
    <h2> Welcome Back!
      <a href="{% url 'posts:for_user' username=user.username%}">
        @{{user.username}}
      </a>
    </h2>

    {% endif %}
    <h2>Groups</h2>
    <p>Welcome to the groups page!</p>
  </div>
  {% if user.is_authenticated %}
  <a href="{% url 'groups:create' %}" class='btn btn-md btn-fill btn-warning'>
    <span class='glyphicon glypicon-plus-sign'>Create New Group</span></a>
  {% endif %}
</div>

{% endblock %}


{% block group_content %}
<div class="col-md-8">
  <div class="list-group">
    {% for group in object_list %}
    <a class='list-group-item' href="{% url 'groups:single' slug=group.slug %}">
      <h3 class='title list-group-item-heading'>{{group.name}}</h3>
      <div class="list-group-item-text container-fluid">
        {{group.description_html|safe}}
        <div class="row">
          <div class="col-md-4">
            <span class='badge'>{{group.members.count}}</span>
            member{{group.members.count|pluralize}}
          </div>
          <div class="col-md-4">
            <span class='badge'>{{group.posts.count}}</span>
            post{{group.posts.count|pluralize}}
          </div>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Google font api -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">


    <link rel="stylesheet" href="{% static 'socialplatform/css/master.css' %}">

  </head>
  <body>
    <nav class='navbar mynav' role='navigation', id='navbar'>
      <div class="container">
        <a class='navbar-brand' mynav href="{% url 'Home'%}">Star Social</a>

        <ul class='nav navbar-nav navbar-right'>
          <!-- If the user has login -->
          {% if user.is_authenticated %}
            <li><a href="#">Post</a></li>
            <li><a href="#">Group</a></li>
            <li><a href="#">Create Group</a></li>
            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="#">Group</a></li>
            <li><a href="{% url 'accounts:login' %}">Log In</a></li>
            <li><a href="{% url 'accounts:signup'%}">Sign Up</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container mycountent">


    {% block content %}

    {% endblock %}

  </div>

  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1> Welcome to Star Social! </h1>
{% endblock %}

templates/test.html
{% extends "base.html"%}
{% block content %}
<h1> You are now logged in </h1>


{% endblock %}

templates/thanks.html
{% extends "base.html"%}
{% block content %}
<h1> Thanks for visiting, come back soon! </h1>


{% endblock %}